# Generated by Django 2.2.7 on 2020-01-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficialingredient',
            name='effect',
            field=models.ManyToManyField(blank=True, to='products.Effect'),
        ),
    ]
