# Generated by Django 2.2.7 on 2020-01-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191212_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficialingredient',
            old_name='effect',
            new_name='effects',
        ),
    ]
