# Generated by Django 2.2.7 on 2020-01-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200120_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='beneficial_ingredient',
            field=models.ManyToManyField(blank=True, to='products.BeneficialIngredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Quantity'),
        ),
    ]
