# Generated by Django 2.2.7 on 2020-01-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200109_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficialingredient',
            old_name='effects',
            new_name='effect',
        ),
    ]
