# Generated by Django 2.2.7 on 2020-01-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200120_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Quantity'),
        ),
    ]
