# Generated by Django 2.2.7 on 2020-01-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200121_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Quantity'),
        ),
    ]
