# Generated by Django 2.2.7 on 2020-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200121_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caution',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
