# Generated by Django 2.2.7 on 2020-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200123_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='children', to='products.Ingredient'),
        ),
    ]
