# Generated by Django 2.2.7 on 2020-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200207_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='organ',
            field=models.ManyToManyField(blank=True, to='products.Organ'),
        ),
    ]
