# Generated by Django 2.2.7 on 2020-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200207_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='oftype',
            field=models.CharField(choices=[('SE', ''), ('ED', 'Evidence'), ('AD', 'Anecdotal'), ('EA', 'EFSA')], default='SE', max_length=2),
        ),
    ]
